Create schema IF NOT EXISTS disasterdash;
use disasterdash;

DROP TABLE IF EXISTS  Quiz;
CREATE TABLE IF NOT EXISTS `Quiz` (
    `ID` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `type` TEXT NOT NULL, /* Types of Disasters*/
    `questionIndex` INTEGER NOT NULL,
    `choiceNum` INTEGER NOT NULL, /* Number of options  (2 or 4)*/
    `question` TEXT NOT NULL,
    `choiceA` TEXT NOT NULL,
    `choiceB` TEXT NOT NULL,
    `choiceC` TEXT,
    `choiceD` TEXT,
    `correct` TEXT NOT NULL,
    `hint` TEXT NOT NULL
);
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`correct`,`hint`) VALUES ('storms',1,2,"Tropical Storms have heavy rain.","True","False","True","Tropical Storms have heavy rain.");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('storms',2,4,"What are hurricanes before they are hurricanes?","Snow","Tornadoes","Rain Storms","Tropical Storms","Tropical Storms","Tropical Storms");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`correct`,`hint`) VALUES ('storms',3,2,"In the mature stage of a storm, it gets more energy.","True","False","True","True");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`correct`,`hint`) VALUES ('storms',4,2,"In the dissipation stage, the hurricanes are the strongest.","True","False","False","False");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`correct`,`hint`) VALUES ('storms',5,2,"You will be notified 24 hours before a hurricane hits.","True","False","True","True");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`correct`,`hint`) VALUES ('storms',6,2,"You can not forecast hurricanes.","True","False","False","False");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('storms',7,4,"How does the Saffir-Simpson Hurricane Scale classify hurricanes by?","Wind Speed","Flooding","Property Damage","All of the above","All of the above","All of the above");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('storms',8,4,"Cold fronts move","Quickly","Slowly","They don't move","They can move slow and fast","Quickly","Quickly");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('storms',9,4,"Warm fronts move","Quickly","Slowly","They don't move","They can move slow and fast","Slowly","Slowly");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('storms',10,4,"After a warm front has moved through, there are","Clear skies and warm weather","Clear skies and cold weather","Stormy weather and colder","Stormy weather and warmer","Clear skies and warm weather","Clear skies and warm weather");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('storms',11,4,"After a cold front has moved through, there is","Dry and cool weather","Dry and warm weather","Stormy cool weather","Stormy warm weather","Dry and cool weather","Dry and cool weather");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('storms',12,4,"The strongest winds of a hurricane are found.","The outer part of the hurricane","Right outside the eye","In the eye","In its arms","Right outside the eye","Right outside the eye");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('storms',13,4,"While a cold front is moving through","There are clear skies","There is stormy weather","There is light rain","There are few clouds","There is stormy weather","There is stormy weather");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('storms',14,4,"Which of the following is the correct term for this definition 'an embankment designed to prevent flooding from a river'?","Terraces","Levees","Valley walls","Deltas","Levees","Levees");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('storms',15,4,"Which of the following describes an outburst flood?","Intense rain storms occur in small steep and impermeable watersheds, often upstream.","Larger watersheds, slow rise, more water moves through them.","Occurs where river slope decreases, temperature drops and the surface of water freezes and collects ice.","Dam failure or artificial causes, sudden release of water, high magnitude and low frequency.","Dam failure or artificial causes, sudden release of water, high magnitude and low frequency.","Dam failure or artificial causes, sudden release of water, high magnitude and low frequency.");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('storms',16,4,"Which of the following describes a downstream flood?","Larger watersheds, slow rise, more water moves through them.","Dam failure or artificial causes, sudden release of water, high magnitude and low frequency.","Larger watersheds, slow rise, more water moves through them.","Occurs where river slope decreases, temperature drops and the surface of water freezes and collects ice.","Larger watersheds, slow rise, more water moves through them.","Larger watersheds, slow rise, more water moves through them.");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('storms',17,4,"Which of the following describes an ice jam flood?","Occurs where river slope decreases, temperature drops and the surface of water freezes and collects ice.","Dam failure or artificial causes, sudden release of water, high magnitude and low frequency.","Larger watersheds, slow rise, more water moves through them.","Intense rain storms occur in small steep and impermeable watersheds, often upstream.","Occurs where river slope decreases, temperature drops and the surface of water freezes and collects ice.","Occurs where river slope decreases, temperature drops and the surface of water freezes and collects ice.");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('storms',18,4,"Which of the following is the correct term for the following definition 'a flat area prone to flooding that lies adjacent to a stream'?","Floodplain","Terrace","Levee","Alluvial fan","Floodplain","Floodplain");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('storms',19,4,"Which of the following are ALL causes of a flood?","Landslides blocking the river, droughts, excess river flow.","Lack of water in the river, coastal storm surges, intense precipitation.","Intense precipitation, excess river flows, coastal storm surges.","Droughts, coastal storm surge, intense precipitation.","Intense precipitation, excess river flows, coastal storm surges.","Intense precipitation, excess river flows, coastal storm surges.");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('storms',20,4,"In regards to flood dynamics and magnitude-frequency which is correct?","A high frequency = high magnitude","A high frequency = low magnitude","A low frequency = low magnitude","A low and high frequency are both low and high magnitudes","A high frequency = low magnitude","A high frequency = low magnitude");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('storms',21,4,"How many years are channels sized to contain water for before a flood would occur?","1-2 years","3-5 years","6 months","2-10 years","1-2 years","1-2 years");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('storms',22,4,"What are the engineering systems used to prevent floods?","Pumps, dams, levees, watersheds","Dams, spillways, levees, dykes, pumps","Channelization, flood proof buildings, terraces, breakwaters","Stream flows, dykes, spillways, breakwaters","Dams, spillways, levees, dykes, pumps","Dams, spillways, levees, dykes, pumps");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('storms',23,4,"What helps a dam by releasing floods so that the water does not overtop and damage or destroy the dam?","Dykes","Spillways","Levees","Pumps","Spillways","Spillways");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('heatwave',1,4,"How does drought contribute to persistently warm temperatures?","Dry air is warmer than humid air","Lack of moisture means less heat is locked into the soil","The energy that would have been used evaporating water heats the atmosphere instead","Drought makes the weather cooler","The energy that would have been used evaporating water heats the atmosphere instead","Think what changes the atmosphere");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('heatwave',2,4,"Which of the following is NOT a symptom of heat exhaustion?","Heavy sweating","Elevated heart rate","Increased appetite","Nausea and vomiting","Increased appetite","Not related to how hungry you are");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('heatwave',3,4,"What causes an “urban heat island,” the phenomenon in which an urban area experiences higher temperatures than outlying areas?","Infrastructure like buildings and roads absorbs and re-emits heat from the sun more than natural landscapes","Cities receive less cooling rain than surrounding areas","The high concentration of glass windows leads to the greenhouse effect","The body heat from the population","Infrastructure like buildings and roads absorbs and re-emits heat from the sun more than natural landscapes","Think the built environment");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('heatwave',4,4,"Since the preindustrial era, how much has human activity caused the globe to warm?","One degree Celsius","Two degrees Celsius","-10.5 degrees Celsius","-16.66 degrees Celsius","-16.66 degrees Celsius","The lowest temperature in the options");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('heatwave',5,4,"The transfer of thermal energy from warm to cooler areas of matter is referred to as","Temperature","Heat","Energy movement","Transfer","Heat","Causes warmth");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('heatwave',6,4,"What is a Heatwave?","Like a hurricane but not","A prolonged period of hot weather","Hot weather","When you see the monthly food bill","A prolonged period of hot weather","Lasts long");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('heatwave',7,4,"How long do heatwaves last?","A month","A year","Several days","5 days","Several days","Several days");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('heatwave',8,4,"When do heatwaves occur?","In the Winter","In the Autumn ","In the Spring","In the Summer","In the Summer","Begins with an “S”");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('heatwave',9,4,"How are heatwaves formed?","By global warming","By no pressure","By high-pressure","By low-pressure","By high-pressure","Increase in pressure");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('heatwave',10,4,"How many people on average die from heatwaves?","1,000 people a year","20 people a year","15,000 people a year","10 people a month","1,000 people a year","Less than 15,000 people a year");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('heatwave',11,4,"Who is more susceptible to heat?","Men","Women","Pets","Trees","Men","Not boys");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('heatwave',12,4,"When was the strongest heatwave?","2022","1999","1947","1913","1913","Before World War 1");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('heatwave',13,4,"Where do heatwaves occur the most?","Africa","North America","Europe","Oceania","North America","Not the obvious continent that first comes to your mind");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('heatwave',14,4,"A heatwave in July 2022 sent temperatures in Britain beyond which mark for the first time in recorded history?","20 degrees Celsius","40 degrees Celsius","50 degrees Celsius","100 degrees Celsius","40 degrees Celsius","Not as hot as a sauna");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('heatwave',15,4,"Furnace Creek holds the record for the hottest ambient air temperature on Earth – 56.66 degrees Celsius in 1913. In what US state can you find Furnace Creek?","California","Nevada","Louisiana","Florida","California","Furnace Creek is located in Death Valley");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('heatwave',16,4,"Warmer summers have led to more frequent “blooms” of harmful cyanobacteria in some freshwater areas of the world. What is the more common name for cyanobacteria?","Blue-green algae","Fire algae","Brown algae","Yellow algae","Blue-green algae","Colour is like turquoise");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('heatwave',17,4,"What was the second hottest day ever recorded in the UK?","10 August 2003 – 38.5 degrees Celsius","25 July 2019 – 38.7 degrees Celsius","18 July 2022 – 38.2 degrees Celsius","19 July 2022 – 40.3 degrees Celsius","25 July 2019 – 38.7 degrees Celsius","Last summer before the Coronavirus pandemic");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('heatwave',18,4,"What is the third hottest day ever recorded in the UK?","25 July 2019 – 38.7 degrees Celsius","19 July 2022 – 40.3 degrees Celsius","10 August 2003 – 38.5 degrees Celsius","18 July 2022 – 38.2 degrees Celsius","10 August 2003 – 38.5 degrees Celsius","Hint – Before the last Athens Olympics");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('heatwave',19,4,"What device is used for measuring temperature?","anemometer","barometer","thermometer","psychrometer","thermometer","Thermal");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('heatwave',20,4,"The energy transferred between the particles of two objects because of the temperature difference between the two objects is called….?","heat","conductor","insulator","temperature","heat","Feels hot");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('soilErosion',1,4,"How long does it take to form 10cm of soil in a moderate climate?","20 – 40 years","200 – 400 years","2000 - 4000 years","20,000 – 40,000 years","2000 - 4000 years","More than 4 centuries");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('soilErosion',2,4,"What causes 56% of soil degradation?","Wind erosion, which is the removal of soil particles by wind","Water erosion, which is the removal of soil particles by water","Chemical deterioration, which is caused by chemical contamination of the soil by a substance","Physical alteration, which is when the structure of the soil is altered(e.g. trampling or heavy machinery)","Water erosion, which is the removal of soil particles by water","Some fluid is involved");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('soilErosion',3,4,"What causes 28% of soil degradation?","Physical alteration, which is when the structure of the soil is altered(e.g. trampling or heavy machinery)","Chemical deterioration, which is caused by chemical contamination of the soil by a substance","Wind erosion, which is the removal of soil particles by wind","Water erosion, which is the removal of soil particles by water","Wind erosion, which is the removal of soil particles by wind","It blows");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('soilErosion',4,4,"What causes 12% of soil degradation?","Physical alteration, which is when the structure of the soil is altered(e.g. trampling or heavy machinery)","Water erosion, which is the removal of soil particles by water","Chemical deterioration, which is caused by chemical contamination of the soil by a substance","Wind erosion, which is the removal of soil particles wind","Physical alteration, which is when the structure of the soil is altered(e.g. trampling or heavy machinery)","Manmade");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('soilErosion',5,4,"What causes 4% of soil degradation?","Water erosion, which is the removal of soil particles by water","Wind erosion, which is the removal of soil particles by wind","Physical alteration, which is when the structure of the soil is altered(e.g. trampling or heavy machinery)","Chemical deterioration, which is caused by chemical contamination of the soil by a substance","Chemical deterioration, which is caused by chemical contamination of the soil by a substance","Involves a substance");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('soilErosion',6,4,"Natural soil erosion is known as:","Geological","Sheet","Rilly","Gully","Geological","Deals with the physical structure and substance of the earth");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('soilErosion',7,4,"The first action of water on soil is that of falling rainfall or …..","Accelerated","Sheet","Rill","Splash","Splash","A synonym of “swash”");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('soilErosion',8,4,"The first step in the soil erosion process is….","Soil transport","Soil deposition","Soil detachment","Soil erosion","Soil detachment","Causes a separation");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('soilErosion',9,4,"The second step in the soil erosion process is…","Soil erosion","Soil deposition","Soil transport","Soil detachment","Soil transport","Like a moving vehicle");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('soilErosion',10,4,"The third and final step in the soil erosion process is ….","Soil deposition","Soil transport","Soil conversion","Soil conversion","Soil deposition","The accumulation of sediments…");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('soilErosion',11,4,"This form of erosion is the gradual and fairly uniform removal of topsoil….","Runoff erosion","Sheet erosion","Rill erosion","Splash erosion","Sheet erosion","Something you make your bed with...");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('soilErosion',12,4,"This form of erosion creates small channels or streamlets in the surface soil","Splash erosion","Gully erosion","Rill erosion","Sheet erosion ","Rill erosion","Caused by runoff water");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('soilErosion',13,4,"What type of landscape terrain/topography is prone to wind erosion?","Flat with few trees","Flat and tree covered","Hilly and tree covered","Hilly with few trees","Flat with few trees","No shade and view not obstructed");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('soilErosion',14,4,"If natural vegetation is removed, the soil is left unprotected resulting in a (an) ………. Rate of soil erosion…","Slowed","Accelerated","Recurrent","None of the above","Accelerated","Occurs very quickly");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('soilErosion',15,4,"What has to happen for wind erosion to occur?","Heavy rain","Moving air dries the soil","Water transports the soil","Air deposits the soil in its final location","Moving air dries the soil","It blows");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('soilErosion',16,4,"Which area in Europe is most affected by soil erosion?","The Baltic  Region","The Mediterranean Region","The Scandinavian Region","Alpine countries","The Mediterranean Region","Where you would find more soil");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('soilErosion',17,4,"Which of these land types yield the highest erosion rates?","Agricultural lands","Shrublands","Forests","Desert","Agricultural lands","Cultivated often");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('soilErosion',18,4,"Which positive effect is associated with Mulching?","It increases the evaporation rate of soils","It removes organic matter from soil","It protects the soil against Wind erosion","It changes the colour of the soil","It protects the soil against Wind erosion","Provides a buffer");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('soilErosion',19,4,"What can occur at the site of an area that is experiencing soil erosion?","Vegetation is able to grow easily","Water pollution is cleared up","Crops are planted at an off-site location","The soil quality is reduced","The soil quality is reduced","The soil is compromised");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('soilErosion',20,4,"Which of the following situations is MOST likely to lead to soil erosion?","An unusually long dry spell for an area","A lack of sun for three weeks in a row","Excessive tilling of a farmer’s field","Adding vegetation to an area","Excessive tilling of a farmer’s field","Disrupts soil structure");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('drought',1,4,"How is climate change likely to affect the number of occurrences of drought?","Droughts will reduce, as the warmer air is able to hold more moisture","It''s unlikely to change to any great amount as the drought hit areas are already an extreme environment","It''s unlikely to change to any great amount as an increase in floods will compensate","Drought will become more common as extreme weather becomes more common","Drought will become more common as extreme weather becomes more common","More common");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('drought',2,4,"What is a drought?","A period of highly variable rainfall","When rivers fall below particular levels","A period of below average precipitation in a specific region","When there is no water for human or animal use","A period of below average precipitation in a specific region","Low rainfall");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('drought',3,4,"Which of these areas is prone to dangerous droughts?","Australia","Canada","Sahel, in North Africa","Bangladesh","Sahel, in North Africa","It spans from the Atlantic Ocean to the Red Sea");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('drought',4,4,"Which of the following is a primary hazard of drought?","Lack of water","Reduced tourism","Damage to crops","Damage to wildlife","Lack of water","Lack of something");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('drought',5,4,"How does the UK ensure the population have a continuous supply of water?","By pumping water out of rivers","By desalination of sea water","By recycling water from sewage","By using reservoirs to store water and boreholes to reach the water table","By using reservoirs to store water and boreholes to reach the water table","By storing it somewhere and...");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('drought',6,4,"Do all droughts have the same effect worldwide?","Yes, since droughts are measured by their effects","No, since average rainfall differs between countries, so below average is a different measurement depending on the climate","Yes, since drought is measured by a specific amount of rainfall","No, since drought is measured on amount of water in the rivers and water table and so can be influenced by a variety of factors","No, since average rainfall differs between countries, so below average is a different measurement depending on the climate","Answer begins with ''No''");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('drought',7,4,"Why does high atmospheric pressure lead to periods of drought?","The descending air moves too fast to rain","The air is descending, which inhibits the formation of cloud","The high pressure forces the rain clouds away","The winds in an area of high pressure blow rain clouds through too fast","The air is descending, which inhibits the formation of cloud","The answer has ''descending'' in it");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('drought',8,4,"Which of these is a secondary hazard of drought?","Water shortage","Desertification","Warmer weather","Hurricanes","Desertification","A type of land degradation");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('drought',9,4,"Why is drought worse in areas that are considered marginal land for farming?","There is no margin of error, as the land is already difficult to grow crops on","People will give up sooner since the margin for profits are much lower","Being on higher ground, they will dry out sooner","Marginal land is less prone to desertification","There is no margin of error, as the land is already difficult to grow crops on","Relates to crop growth");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('drought',10,4,"Which of the following is not a way that households can reduce water use?","Having a water meter fitted","Using a hosepipe more","Reducing the size of the toilet cistern","Taking showers rather than baths","Using a hosepipe more","Using something more");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('drought',11,4,"Countries around which sea experience rain in the winter, and droughts in the summer?","Caribbean Sea","Mediterranean Sea","Baltic Sea","North Sea","Mediterranean Sea","Near Greece");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('drought',12,4,"How can dams cause drought?","By reducing rainfall levels","By reducing water levels downstream","By flooding land behind the dam wall","None of the options","By reducing water levels downstream","Has something to do with water levels");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('drought',13,4,"Which is a better response to drought?","Food aid","Development aid","Water aid","None of the options","Development aid","Not food/water aid");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('drought',14,4,"Which of the following human activies can trigger a drought?","Deforestation","Urbanisation","Over-fishing","None of the options","Deforestation","Removal of something");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('drought',15,4,"What human factor causes drought in the Sahel?","Reduced rainfall","Overcultivation","The season","Over-fishing","Overcultivation","Something excessive");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('drought',16,4,"What is not true about drought?","It is a long period with less-than-normal precipitation","It can be caused by people overusing and over-populating an area","Higher-the-usual temperatures can sometimes be part of it","Droughts always arrive fast","Droughts always arrive fast","They arrive...");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('drought',17,4,"What is a meteorological drought?","A drought that is caused by changes in the weather and it is a comparison with historical amounts of precipitation","When water amounts are lower than what is needed to grow crops","Low amounts of water in natural systems like streams, river, groundwater and snowpack","When people''s demand for water is higher than the amount of water available","A drought that is caused by changes in the weather and it is a comparison with historical amounts of precipitation","Compares precipitation to a historical average");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('drought',18,4,"What is an agricultural drought?","When people''s demand for water is higher than the amount of water available","A drought that is caused by changes in the weather and it is a comparison with historical amounts of precipitation","Low amounts of water in natural systems like streams, river, groundwater and snowpack","When water amounts are lower than what is needed to grow crops","When water amounts are lower than what is needed to grow crops","Its lower than what is required for something");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('drought',19,4,"What is a hydrological drought?","Low amounts of water in natural systems like streams, river, groundwater and snowpack","When people''s demand for water is higher than the amount of water available","A drought that is caused by changes in the weather and it is a comparison with historical amounts of precipitation","When water amounts are lower than what is needed to grow crops","Low amounts of water in natural systems like streams, river, groundwater and snowpack","Low amounts of water in something");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('drought',20,4,"How does a drought end?","If a little rainfall is recorded","During a frost","When no rainfall is recorded","When rains that soak into the soil and replenish the groundwater occur","When rains that soak into the soil and replenish the groundwater occur","Relates to soil");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('epidemics',1,4,"What is an Epidemic?","A Tropical Storm","A heatwave above 50 degrees celsius","a widespread occurrence of an infectious disease in a community at a particular time","A toxic waste in the form of a liquid that damages soil","a widespread occurrence of an infectious disease in a community at a particular time"," Health related Issue");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('epidemics',2,4,"An epidemic that becomes unusually widespread and even global in its reach is referred to as a?","pandemic","hyperendemic","Spanish flu","torpedo","pandemic","starts with the latin word for ‘of everything’ or ‘all’");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('epidemics',3,4,"A disease vector is a(n)?","symptom of a disease","environmental condition associated with a disease","organism that transmits a disease","Element of the soil that casues disease","organism that transmits a disease","usually small flying insects");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('epidemics',4,4," Epidemiologists are interested in learning about"," the causes of diseases and how to cure or control them"," the frequency and geographic distribution of diseases"," the causal relationships between diseases","all of the above","all of the above","The answer is more comprehensive");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('epidemics',5,4," Diseases that are always present in a community, usually at a low, more or less constant, frequency are classified as having an ____________ pattern.","epidemic","endemic","pandemic","supersonic","endemic","The word that means ‘regularly found’");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('epidemics',6,4,"Which of the following statements is true concerning epidemic diseases?","They are usually not very contagious.","At the end of an epidemic, a disease spreads at an increasing rate and then abruptly disappears.","They usually appear and disappear seasonally.","They are only transmitted through liquids","They usually appear and disappear seasonally.","changes in the environment");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('epidemics',7,4,"Which of the following things cause malaria?","mosquitoes","plasmodia (singular plasmodium)","red blood cells","rats","plasmodia (singular plasmodium)","parasites on red blood cells ");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('epidemics',8,4,"About what fraction of the people in the world have chronic diseases that are vector-borne?","1/4","1/2","3/4","1/10","1/2","Tropical and subtropical regions are the most effected.");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('epidemics',9,4," Most of the major health problems in the poorer nations are due to ____________________ .","parasitic worms and microorganisms","psychological tension resulting from work","air pollution","stress","parasitic worms and microorganisms","The major cause of disease in developed nations before the 20th century. ");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('epidemics',10,4," The prime cause of illness resulting in death in the poor countries of the tropical and subtropical regions today is __________________ .","lyme disease","plague","malaria","cholera","malaria","close to 100mill new cases reported annually around the world");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('epidemics',11,4," Diseases that are due mostly to environmental changes, increased population densities, and pollution that result from modernization in third world nations are referred to as:","diseases of poverty","diseases of development"," schistosomiasis","diseases of tropics","diseases of development","poor sanitisation in urban centers, industrial pollution are examples ");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('epidemics',12,4,"Which of the following statements is true?","Modern medicine has at times been responsible for causing health problems."," Malnutrition has been essentially eliminated in the developed countries.","Persistent undernourishment among children rarely results in serious health problems.","Lack of dietary balance does not contribute to illness","Modern medicine has at times been responsible for causing health problems.","unexpected side effects");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`correct`,`hint`) VALUES ('epidemics',13,2,"True or False? Cholera cannot move across the world.","True","False","False","Carried by individuals");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('epidemics',14,4,"What is crisis mapping?","The use of open-source geospatial data and crowdsourcing to map an ongoing emergency","The use of local knowledge to map viral pathogenesis","The use of household interviews to map levels of panic by area","The use of expert epidemiological knowledge to predict the spread of a crisis","The use of open-source geospatial data and crowdsourcing to map an ongoing emergency","websites can engage citizens in the effort of mapping disease");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('epidemics',15,4,"What are some important patterns to study during epidemics?","Trade routes","Populations and locations of a reservoir host","Water systems","All of the above can be important patterns to monitor during epidemics","All of the above can be important patterns to monitor during epidemics","Patterns can help to track, predict and control spread of disease");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('epidemics',16,4,"The hallmark feature of an analytic epidemiologic study is: ","Use of an appropriate comparison group","Laboratory confirmation of the diagnosis ","Publication in a peer-reviewed journal ","Statistical analysis using logistic regression ","Use of an appropriate comparison group","Something required to measure agains");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('epidemics',17,4," When analyzing surveillance data by age, which of the following age groups is preferred?","1-year age groups","5-year age groups","10-year age groups","Depends on the disease","Depends on the disease","Different diseases have different age distributions ");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('epidemics',18,4," The epidemiologic triad of disease causation refers to:","Agent, host, environment","Time, place, person","Source, mode of transmission, susceptible host","John Snow, Robert Koch, Kenneth Rothman","Agent, host, environment","The most obvious three factors");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`choiceC`,`choiceD`,`correct`,`hint`) VALUES ('epidemics',19,4,"How can the changing climate and weather affect human health? ","Increase frequency or severity of existing health risks ","Introduce health risks to geographic regions where they have not previously occurred ","Shift the timing of seasonal health risks ","All of the above","All of the above","Select a more comprehensive answer");
INSERT INTO `Quiz` (`type`,`questionIndex`,`choiceNum`,`question`,`choiceA`,`choiceB`,`correct`,`hint`) VALUES ('epidemics',20,2," Depression and post-traumatic stress disorder (PTSD) rates increase after climate- and weather-related disasters.","True","False","True","People can experience serious emotional consequences.");

